AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  todo-api

  Sample SAM Template for todo-api

Globals:
  Function:
    Timeout: 3

Resources:
  AutoConfirmUserFunction: !include templates/functions/auto-confirm-user.yaml
  AutoConfirmUserPermission: !include templates/auto-confirm-user-permission.yaml
  UserPool: !include templates/user-pool.yaml
  UserPoolClient: !include templates/user-pool-client.yaml
  TodoTable: !include templates/todo-table.yaml
  AppSyncApi: !include templates/appsync-api.yaml
  AppSyncSchema: !include templates/appsync-schema.yaml
  AppSyncTodoTableDataSource: !include templates/appsync-todo-table-source.yaml
  AppSyncAllTodosQueryResolver: !include templates/resolvers/all-todos.yaml
  AppSyncDeleteTodoQueryResolver: !include templates/resolvers/delete-todo.yaml
  AppSyncGetTodoQueryResolver: !include templates/resolvers/get-todo.yaml
  AppSyncSaveTodoQueryResolver: !include templates/resolvers/save-todo.yaml
  IdentityPool: !include templates/identity-pool.yaml
  IdentityPoolAuthenticatedRole: !include templates/identity-pool-authenticated-role.yaml
  IdentityPoolRoleAttachment: !include templates/identity-pool-role-attachment.yaml
  IdentityPoolUnauthenticatedRole: !include templates/identity-pool-unauthenticated-role.yaml
  DynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-appsync-dynamodb-role
      ManagedPolicyArns:
        - Ref: AppSyncDynamoDBPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com
    DependsOn:
      - AppSyncDynamoDBPolicy
  AppSyncDynamoDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: /appsync/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
            Resource:
              Fn::Join: [ "", [ !GetAtt TodoTable.Arn, "*" ] ]

Outputs:
  UserPool:
    Description: "UserPool ID"
    Value: !Ref UserPool
  UserPoolClient:
    Description: "UserPoolClient ID"
    Value: !Ref UserPoolClient
